#!/usr/bin/env python3
"""
Generate the full MARC-8 mapping tables from the Library of Congress
`codetables.xml` (https://www.loc.gov/marc/specifications/codetables.xml):

    python3 tools/gen_marc8_tables.py codetables.xml

writes src/include/marc/marc8_tables.hpp, the table src/core/marc8.cpp
compiles.  With --pytable it also writes the Python form of the same data,
which the reference implementation in the Python companion imports as
marc8_tables.py, so the C++ decoder and the Python reference read one source
of truth.  Both outputs are committed in their own repositories;
regenerating either requires only this script and LC's XML.

    python3 audit/tools/gen_marc8_tables.py audit/data/codetables.xml \
        --pytable ../marcduckpy/tools/marc8_tables.py

Normalisation: LC lists some sets in G0 form (0x21-0x7E) and some in G1 form
(0xA1-0xFE).  Single-byte codes are stored masked to 7 bits so one table
serves both designations; the decoder masks the input byte the same way.
EACC codes are three bytes (0x21-0x7E each), stored as 24-bit keys.

Clean-room note: the input is LC's published table.  Do not derive mappings
from MarcEdit, pymarc, or marc4j.
"""
from __future__ import annotations

import argparse
import pathlib
import sys
import xml.etree.ElementTree as ET

import os
ROOT = pathlib.Path(os.environ.get("MARC21_ROOT", os.getcwd()))
SELF = pathlib.Path(__file__).resolve().parent


def load_sets(xml_path: str):
    tree = ET.parse(xml_path)
    sets = []  # (iso, name, is_multibyte, {key: (ucs, combining)})
    for cs in tree.getroot().iter("characterSet"):
        iso = int(cs.get("ISOcode"), 16)
        name = cs.get("name")
        multibyte = iso == 0x31  # EACC
        table: dict[int, tuple[int, bool]] = {}
        for code in cs.iter("code"):
            marc = code.findtext("marc")
            ucs = code.findtext("ucs")
            alt = code.findtext("alt")
            if not marc:
                continue
            if not ucs and not alt:
                continue  # truly unmapped (a few EACC codes)
            key = int(marc, 16)
            if not multibyte:
                if key < 0x21:
                    continue  # control characters pass through the decoder
                key &= 0x7F
            # Empty primary <ucs> with an <alt> means LC's preferred mapping
            # is "nothing" (e.g. EC, ligature second half: EB alone becomes
            # the spanning U+0361).  Stored as ucs=0 -> decoder emits nothing.
            cp = int(ucs, 16) if ucs else 0
            combining = (code.findtext("isCombining") or "").strip() == "true"
            # First entry wins on duplicates (LC lists alternates later).
            table.setdefault(key, (cp, combining))
        sets.append((iso, name, multibyte, dict(sorted(table.items()))))
    return sets


def emit_cpp(sets) -> str:
    out = ["// GENERATED by tools/gen_marc8_tables.py from LC codetables.xml."]
    out.append("// Do not edit by hand; regenerate instead.")
    out.append("#pragma once")
    out.append("#include <cstdint>")
    out.append("namespace marc {")
    out.append("struct Marc8Entry { uint32_t marc; uint32_t ucs; bool combining; };")
    out.append("struct Marc8Set { const Marc8Entry *entries; unsigned count; bool multibyte; };")
    idents = []
    for iso, name, multibyte, table in sets:
        ident = f"MARC8_SET_{iso:02X}"
        idents.append((iso, ident))
        out.append(f"// {name} (ISO {iso:02X})")
        rows = ",".join(f"{{0x{k:X},0x{u:X},{int(c)}}}" for k, (u, c) in table.items())
        out.append(f"inline constexpr Marc8Entry {ident}_E[] = {{{rows}}};")
        out.append(f"inline constexpr Marc8Set {ident} = "
                   f"{{{ident}_E, {len(table)}, {str(multibyte).lower()}}};")
    out.append("inline const Marc8Set *Marc8SetFor(uint8_t designation) {")
    out.append("\tswitch (designation) {")
    for iso, ident in idents:
        out.append(f"\tcase 0x{iso:02X}: return &{ident};")
    out.append("\tdefault: return nullptr;")
    out.append("\t}")
    out.append("}")
    out.append("} // namespace marc")
    return "\n".join(out) + "\n"


def emit_py(sets) -> str:
    out = ["# GENERATED by tools/gen_marc8_tables.py from LC codetables.xml."]
    out.append("# Do not edit by hand; regenerate instead.")
    out.append("# {iso: (multibyte, {key: (ucs, combining)})}")
    out.append("MARC8_SETS = {")
    for iso, name, multibyte, table in sets:
        out.append(f"    # {name}")
        rows = ",".join(f"0x{k:X}:(0x{u:X},{int(c)})" for k, (u, c) in table.items())
        out.append(f"    0x{iso:02X}: ({multibyte}, {{{rows}}}),")
    out.append("}")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate the MARC-8 tables from LC codetables.xml.")
    ap.add_argument("xml", help="path to LC codetables.xml")
    ap.add_argument("--check", metavar="HEADER",
                    help="regenerate and byte-compare against HEADER instead of "
                         "writing anything; exit 1 on any difference")
    ap.add_argument("--pytable", metavar="PATH",
                    help="also write the Python table here; the reference "
                         "implementation in the Python companion imports it as "
                         "marc8_tables.py, so both languages read one source")
    args = ap.parse_args()

    sets = load_sets(args.xml)
    header = emit_cpp(sets)

    # Verification mode: prove the committed header is still exactly what this
    # script produces from LC's data, so a drifted header cannot pass unnoticed.
    if args.check:
        committed = pathlib.Path(args.check).read_text()
        if committed == header:
            print(f"OK: generated header is byte-identical to {args.check}")
            return
        sys.stderr.write(f"MISMATCH: {args.check} is not what this script generates\n")
        want = header.splitlines()
        have = committed.splitlines()
        for i, (a, b) in enumerate(zip(have, want), 1):
            if a != b:
                sys.stderr.write(f"  first difference at line {i}\n")
                break
        else:
            sys.stderr.write(f"  line counts differ: {len(have)} committed, "
                             f"{len(want)} generated\n")
        sys.exit(1)

    (ROOT / "src" / "include" / "marc" / "marc8_tables.hpp").write_text(header)
    if args.pytable:
        pathlib.Path(args.pytable).write_text(emit_py(sets))
    for iso, name, multibyte, table in sets:
        print(f"{iso:02X} {name}: {len(table)} codes{' (multibyte)' if multibyte else ''}")


if __name__ == "__main__":
    main()
